### ISSUE TITLE
Bibliographic Import for AWS Goobi

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#77]
This will be done by uploading marc-xml files packed into a zip file. This has already been discussed with Rioghnach in the intranda internal support tracker here: https://support.intranda.com/issues/12531

**Comment by rsehr** [comment]
We installed the new import plugin for bibliographic metadata on winslow. 

You can use the same files as with the old import where you selected files from a folder. 
To use it, you can open the mass import screen. But instead of choosing import from folder, you can select file upload import.

Here you can select the plugin 'plugin_import_fileupload_wellcome' from the list. Afterwards you can upload a single marc.xml file or a zip file containing many marc xml files. All files you uploaded will be imported with the same mechanism we used for the old Millennium Import plugin. 

MMOs can be imported on the file upload import screen as well. Here you must select the Multiple Manifestation Millennium Import. But you can only upload single marc xml files. Importing many files in one is not possible with this plugin.

**Comment by Rioghnach** [comment]
I think that this will work fine in theory. Can I check if you're still looking into the possibility of using Z39.50 for bulk bibliographic import? https://support.intranda.com/issues/12531 This would mean that we wouldn't need to manually export the MARC from Sierra, create MARC XML using MARC Edit, and import the metadata using the file import function (either individually or in bulk zipped up). This is quite an onerous process and it would be great if it could be simplified.

**Comment by rsehr** [comment]
We stopped the idea of using the Z39.50 interface for several reasons:
you wrote that you want to suppress unfinished records,
you want to import multiple records in a batch, 
you want to edit some marc files using MARC Edit to correct the data,
you have special fields like the leader6 field, that cannot be imported using the regular marc import

All those needs cannot be fulfilled right now. I can see a solution to import multiple records in a batch, but for the other points we have no solution when we import the data through Z39.50. But when you don't bother about the other reasons, we can implement a mechanism to get the data from the interface.

**Comment by Rioghnach** [comment]
Thanks for clarifying Robert. I didn't know that the leader6 field was a special field as it's a standard MARC field (but not for Goobi clearly). We would need to suppress/un-suppress records in Sierra as we do with the Internet Archive. We sometimes need to make small edits using MARC Edit, this is definitely an important use case. 

Can we test using a zip file in Winslow?

**Comment by rsehr** [comment]
Yes, it is installed on winslow

**Comment by rsehr** [comment]
Also it is installed and tested on AWS
